### ISSUE TITLE
Customizing the sidebar

### ISSUE THREAD

**Issue by jsonmaur** [timberio/gitdocs#106]
Things that should be customizable in the sidebar:
- Link ordering
- Custom grouping with headers/vertical lines
- Alternate sidebars per page
- Static link items anywhere in the tree
- Icons

Requirements:
- Should be able to define custom items on a few links only, without having to re-define every link.
- Need to do a deep merge on the default nav tree generated in the manifest (based on the file structure) and the user-provided nav tree.
- A source of truth on each sidebar item that cannot be duplicated. This is required to do a deep merge without duplicating links.
- Should be able to define git sources inline, whether in the front matter or in the config sidebar object.
- Be able to merge from configs in external sources.

Options discussed so far:
- Adding an `order` key in the front matter that's a number. Links will be ordered in ascending order based on the number. Pros to this approach: the front matter will always be the source of truth for a page's metadata, including where it is in the sidebar (I don't like being able to override front matter in the config file), file structure will always map 1-to-1 with the sidebar structure. Cons: is it's difficult to customize/order stuff that doesn't have it's own file (such as a folder with no `index.md`.)
- A custom `sidebar` on the config file that re-defines items in the structure you want to customize, and merging with the default sidebar based on the url. Pros: more flexible and easier to define/see a custom structure. Cons: Difficult to do a deep merge with the default sidebar, more verbose to define something custom for a deeply-nested sidebar link.

[Notes from whiteboard session](https://cl.ly/191i2f43430c)

**Comment by jsonmaur** [comment]
After trying out several different solutions, this is what feels the most flexible and easy to define: adding a `sidebar` item to the front matter of each file, which will be the source of truth for its children items (no overrides in `.gitdocs.json` after all.)

In it's simplest form:
###### index.md
```yaml
---
sidebar:
  - timber-for-languages
  - timber-for-platforms
  - timber-app
  - timber-service
  - timber-guides
  - timber-concepts

// or to change the order of a few items without redefining each item

sidebar_prepend:
  - timber-for-languages
  - timber-for-platforms
---
```

###### timber-for-languages/index.md
```yaml
---
sidebar_append:
  - other
---
```

Items under `sidebar` could be one of two things:
- a string, in which case it would be the url and we would auto-generate the title and make it a simple internal link
- an object with keys for `title`, `link`, `icon`, `divider`, etc.

The link location would be the unique key when merging a custom sidebar with the generated one. For example, to prepend `timber-for-languages` to the top of the sidebar list, you'd define `sidebar_prepend` instead of `sidebar` and it will pluck it out of the generated sidebar and prepend it to the final one.

If you want to customize the order of something that doesn't have an `index.md` (which obviously can't have its own front matter), you could put it in the front matter of its parent and use an `items`/`items_prepend`/`items_append` key. For example:

```yaml
sidebar:
  - timber-for-languages
  - link: timber-for-platforms
    icon: some_icon.svg
    items:
      - ruby
      - node
      - other
    // or just
    items_append:
      - other
```

This prevents having to define an arbitrary `order` index for each item and instead relies on native array indexes (as it should.) It also allows you to customize sidebar items for a deeply nested route without having to manually define the structure all the way down. It makes sense to always keep the file structure as the source of truth for the sidebar structure, and is a lot simpler than trying to merge a generated sidebar object with a custom sidebar object that could potentially be in a different format.

### More examples

#### External sidebar links
```yaml
sidebar:
  - timber-for-languages
  - title: API Documentation
    link: https://api-docs.timber.io/
```

#### Grouped items without index pages
```yaml
sidebar:
  - title: Timber for Languages
    items:
      - node
      - ruby
  - title: Timber for Platforms
    items:
      - heroku
      - linux
```

#### Dividers
```yaml
sidebar:
  - timber-for-languages
  - divider: true
  // or potentially
  - component: Divider
  - timber-for-platforms
```

#### Disable the sidebar completely for a page
```yaml
sidebar: false
```
